"""added output column to Input

Revision ID: 1f883e4af01d
Revises: 
Create Date: 2020-09-17 20:19:36.270944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f883e4af01d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inputs', sa.Column('output', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_inputs_output'), 'inputs', ['output'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_inputs_output'), table_name='inputs')
    op.drop_column('inputs', 'output')
    # ### end Alembic commands ###
