"""updated column name to source_lang_id

Revision ID: 29b284c5fb3e
Revises: 
Create Date: 2020-09-22 15:02:49.190048

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29b284c5fb3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('translation_models', sa.Column('source_lang_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('translation_models', 'source_lang_id')
    # ### end Alembic commands ###
