"""Test: changed Input table to Job table

Revision ID: 4d8b659dd9ff
Revises: 2da13d8d62d7
Create Date: 2020-09-21 14:32:30.961708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d8b659dd9ff'
down_revision = '2da13d8d62d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('input', sa.String(length=64), nullable=True),
    sa.Column('output', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_input'), 'jobs', ['input'], unique=True)
    op.create_index(op.f('ix_jobs_output'), 'jobs', ['output'], unique=True)
    op.drop_index('ix_inputs_input', table_name='inputs')
    op.drop_index('ix_inputs_output', table_name='inputs')
    op.drop_table('inputs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inputs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('input', sa.VARCHAR(length=64), nullable=True),
    sa.Column('output', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inputs_output', 'inputs', ['output'], unique=1)
    op.create_index('ix_inputs_input', 'inputs', ['input'], unique=1)
    op.drop_index(op.f('ix_jobs_output'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_input'), table_name='jobs')
    op.drop_table('jobs')
    # ### end Alembic commands ###
